# Generated by Django 5.2 on 2025-05-02 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='event_preferences',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='booking_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='BookingId'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_history', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
